### ISSUE TITLE
Migrate to PHPMailer

### ISSUE THREAD

**Issue by lahdekorpi** [sundflux/webvaloa#105]
Since composer is used, add PHPMailer to the requirements (like most software do) and allow configuration via `config.php`

This also fixes #7 and #103 
Implementing #2 is potentially also easier.

**Comment by lahdekorpi** [comment]
For backwards compatibility the existing Mail class should stay as is.
And the new mailer can be replaced in Login controller.

**Comment by lahdekorpi** [comment]
A wrapper is still needed for PHPMailer to make configuration easier.

**Comment by sundflux** [comment]
done, needs testing
