### ISSUE TITLE
Locale not available in view

### ISSUE THREAD

**Issue by lahdekorpi** [sundflux/webvaloa#112]
This data should be accessible from a plugin (using navigation plugin for this makes sense as it is needed when navigation is in use).

**Comment by lahdekorpi** [comment]
Actually, would it make more sense to detach this to it's own plugin @sundflux ?

**Comment by lahdekorpi** [comment]
Good enough.

**Comment by sundflux** [comment]
This is incorrect, locale is available globally from any XSL: /page/common/locale

**Comment by sundflux** [comment]
And plugins should use the standard \Webvaloa\Webvaloa::getLocale();
