### ISSUE TITLE
Non-admins have access to globals

### ISSUE THREAD

**Issue by lahdekorpi** [sundflux/webvaloa#131]
Users with access to content controller that aren't administrator have access to /content_article/globals

**Comment by sundflux** [comment]
Of course they have. Globals are NOT any administrative settings, those are not "worthy" more than article data. Settings module can handle settings in controller-basis (combine that with a plugin to load controller settings anywhere if that's whats required). This is by design.

**Comment by lahdekorpi** [comment]
Given that selected categories can be configured to restrict edit access to only certain roles, the same functionality should be extended to globals. Could probably be done with existing ACL functionality, just by providing a UI?

**Comment by sundflux** [comment]
UI to do what, exactly?

Don't oversimplify this based on a single project requirement. Every field group can be assigned to any category, this will just open a can of worms with ACL. Plan your projects on how the system works, or do a plugin.

**Comment by sundflux** [comment]
If your project needs "admin settings", why not do a category based on these privileges and fields required for it? Global fields are meant exactly what they sound like - being global. Site titles and whatever. This "issue" has no "solution" so its just wontfixit
