### ISSUE TITLE
LIBVALOA_EXTENSIONSPATH in config.php not loaded

### ISSUE THREAD

**Issue by lahdekorpi** [sundflux/webvaloa#159]
`DEFINE('LIBVALOA_EXTENSIONSPATH', '/var/www/mywebsite/app/vendor/');` in config.php gets ignored.

Just as a test, putting it in index.php works fine. Older versions worked fine.

**Comment by sundflux** [comment]
It's not used anymore, use regular php include path for vendor dirs
