### ISSUE TITLE
Imagick fixes

### ISSUE THREAD

**Issue by lahdekorpi** [sundflux/webvaloa#18]
1) Never, ever upscale images

2) Allow users to retrieve images without resizing or cropping them (but maybe by giving them max size)

**Comment by sundflux** [comment]
I disagree on 1. I put layout presentation as priority, it's up to the user to use large enough images.

I don't agree on point 2 either. Displaying only magick'ed images on the page works as kind of 'watermark' at best. Website itself can implement linking to the original image.
