### ISSUE TITLE
Allow custom regex verifications for fields

### ISSUE THREAD

**Issue by lahdekorpi** [sundflux/webvaloa#4]
In the field editor, allow adding custom regular expressions for fields to validate user input.

**Comment by lahdekorpi** [comment]
Using HTML5 input pattern and a polyfill would probably be enough for this.
JavaScript support is already required and there is no real need to validate on the backend side.

**Comment by lahdekorpi** [comment]
http://caniuse.com/#feat=input-pattern

**Comment by sundflux** [comment]
html5 pattern="" support implemented. only implemented for text type field. rest will work automatically after field xsl templates get updated. help appreciated for this!
