### ISSUE TITLE
SMTP support for Webvaloa\Mail

### ISSUE THREAD

**Issue by lahdekorpi** [sundflux/webvaloa#7]
Extend Webvaloa\Mail to support SMTP.

Borrow ideas from: 
https://github.com/cakephp/cakephp/blob/master/lib/Cake/Network/Email/SmtpTransport.php
or
https://github.com/jasonjohnson/php-smtp
or something

**Comment by sundflux** [comment]
Gonna leave this out as its redurant to phpmailer migration
